import type { Reservation, Room } from '@/types';
import { uid } from '@/lib/utils';

const today = new Date();
const offset = (days: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
};

export function seedRooms(): Room[] {
  return [
    // Ground floor — 6 rooms
    {
      id: 'room-001',
      number: '001',
      type: 'family',
      capacity: 4,
      pricePerNight: 2500,
      amenities: ['Wi-Fi', 'TV', 'Air conditioning'],
      isActive: true,
    },
    {
      id: 'room-002',
      number: '002',
      type: 'family',
      capacity: 4,
      pricePerNight: 2500,
      amenities: ['Wi-Fi', 'TV', 'Air conditioning', 'Coffee maker'],
      isActive: true,
    },
    {
      id: 'room-003',
      number: '003',
      type: 'family',
      capacity: 4,
      pricePerNight: 2500,
      amenities: ['Wi-Fi', 'TV', 'Air conditioning'],
      isActive: true,
    },
    {
      id: 'room-004',
      number: '004',
      type: 'family',
      capacity: 4,
      pricePerNight: 2500,
      amenities: ['Wi-Fi', 'TV', 'Air conditioning', 'Coffee maker'],
      isActive: true,
    },
    {
      id: 'room-005',
      number: '005',
      type: 'family',
      capacity: 4,
      pricePerNight: 2500,
      amenities: ['Wi-Fi', 'TV', 'Air conditioning'],
      isActive: true,
    },
    {
      id: 'room-006',
      number: '006',
      type: 'family',
      capacity: 4,
      pricePerNight: 2500,
      amenities: ['Wi-Fi', 'TV', 'Air conditioning', 'Coffee maker'],
      isActive: true,
    },
    // 1st floor — 5 rooms
    {
      id: 'room-101',
      number: '101',
      type: 'duplex',
      capacity: 6,
      pricePerNight: 4000,
      amenities: ['Wi-Fi', 'Smart TV', 'Mini bar', 'Balcony'],
      isActive: true,
    },
    {
      id: 'room-102',
      number: '102',
      type: 'duplex',
      capacity: 6,
      pricePerNight: 4000,
      amenities: ['Wi-Fi', 'Smart TV', 'Mini bar', 'Workspace'],
      isActive: true,
    },
    {
      id: 'room-103',
      number: '103',
      type: 'duplex',
      capacity: 6,
      pricePerNight: 4000,
      amenities: ['Wi-Fi', 'Smart TV', 'Mini bar', 'Balcony'],
      isActive: true,
    },
    {
      id: 'room-104',
      number: '104',
      type: 'duplex',
      capacity: 6,
      pricePerNight: 4000,
      amenities: ['Wi-Fi', 'Smart TV', 'Mini bar', 'Workspace'],
      isActive: true,
    },
    {
      id: 'room-105',
      number: '105',
      type: 'duplex',
      capacity: 6,
      pricePerNight: 4000,
      amenities: ['Wi-Fi', 'Smart TV', 'Mini bar', 'Balcony'],
      isActive: true,
    },
    // 2nd floor — 5 rooms
    {
      id: 'room-201',
      number: '201',
      type: 'family',
      capacity: 4,
      pricePerNight: 3500,
      amenities: ['Wi-Fi', 'Smart TV', 'Mini bar', 'Balcony', 'Workspace'],
      isActive: true,
    },
    {
      id: 'room-202',
      number: '202',
      type: 'duplex',
      capacity: 6,
      pricePerNight: 5500,
      amenities: ['Wi-Fi', 'Smart TV', 'Mini bar', 'Living room', 'Balcony'],
      isActive: true,
    },
    {
      id: 'room-203',
      number: '203',
      type: 'family',
      capacity: 4,
      pricePerNight: 3500,
      amenities: ['Wi-Fi', 'Smart TV', 'Mini bar', 'Workspace', 'Balcony'],
      isActive: true,
    },
    {
      id: 'room-204',
      number: '204',
      type: 'duplex',
      capacity: 6,
      pricePerNight: 5500,
      amenities: ['Wi-Fi', 'Smart TV', 'Mini bar', 'Living room', 'Kitchen'],
      isActive: true,
    },
    {
      id: 'room-205',
      number: '205',
      type: 'duplex',
      capacity: 8,
      pricePerNight: 7500,
      amenities: ['Wi-Fi', 'Smart TV', 'Jacuzzi', 'Living room', 'Kitchen', 'Balcony', 'Workspace'],
      isActive: true,
    },
  ];
}

export function seedReservations(): Reservation[] {
  return [
    {
      id: uid(),
      roomId: 'room-001',
      guestName: 'Eleanor Pena',
      guestEmail: 'eleanor.pena@example.com',
      guestPhone: '+91 98765 43210',
      guestCity: 'Mumbai',
      checkIn: offset(-3),
      checkOut: offset(1),
      arrivalDate: offset(-3),
      arrivalTime: '14:00',
      arrivalMode: 'walkin',
      isForeignGuest: false,
      paymentMethod: 'cash',
      mealPlan: 'AP',
      noOfRooms: 1,
      paxAdults: 2,
      paxChildren: 1,
      paxExtra: 0,
      status: 'checked-in',
      totalPrice: 2500 * 4,
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
      notes: 'Late check-in requested.',
    },
    {
      id: uid(),
      roomId: 'room-002',
      guestName: 'Bessie Cooper',
      guestEmail: 'bessie.cooper@example.com',
      guestPhone: '+91 98765 43211',
      guestCity: 'Delhi',
      checkIn: offset(0),
      checkOut: offset(3),
      arrivalDate: offset(0),
      arrivalTime: '12:00',
      arrivalMode: 'ota',
      isForeignGuest: false,
      paymentMethod: 'gpay',
      mealPlan: 'MAP',
      noOfRooms: 1,
      paxAdults: 2,
      paxChildren: 0,
      paxExtra: 0,
      status: 'confirmed',
      totalPrice: 2500 * 3,
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: uid(),
      roomId: 'room-101',
      guestName: 'Jenny Wilson',
      guestEmail: 'jenny.wilson@example.com',
      guestPhone: '+91 98765 43212',
      guestCity: 'Bangalore',
      checkIn: offset(1),
      checkOut: offset(4),
      arrivalDate: offset(1),
      arrivalTime: '15:00',
      arrivalMode: 'travel-agent',
      isForeignGuest: true,
      paymentMethod: 'gpay',
      mealPlan: 'CP',
      noOfRooms: 1,
      paxAdults: 2,
      paxChildren: 2,
      paxExtra: 0,
      status: 'confirmed',
      totalPrice: 4000 * 3,
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: uid(),
      roomId: 'room-102',
      guestName: 'Robert Fox',
      guestEmail: 'robert.fox@example.com',
      guestPhone: '+91 98765 43213',
      guestCity: 'Chennai',
      checkIn: offset(-7),
      checkOut: offset(-4),
      arrivalDate: offset(-7),
      arrivalTime: '13:00',
      arrivalMode: 'company',
      isForeignGuest: false,
      paymentMethod: 'cash',
      mealPlan: 'EP',
      noOfRooms: 1,
      paxAdults: 1,
      paxChildren: 0,
      paxExtra: 1,
      status: 'checked-out',
      totalPrice: 4000 * 3,
      createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
    {
      id: uid(),
      roomId: 'room-201',
      guestName: 'Cody Fisher',
      guestEmail: 'cody.fisher@example.com',
      guestPhone: '+91 98765 43214',
      guestCity: 'Pune',
      checkIn: offset(2),
      checkOut: offset(6),
      arrivalDate: offset(2),
      arrivalTime: '16:00',
      arrivalMode: 'walkin',
      isForeignGuest: false,
      paymentMethod: 'gpay',
      mealPlan: 'MAP',
      noOfRooms: 1,
      paxAdults: 2,
      paxChildren: 2,
      paxExtra: 0,
      status: 'confirmed',
      totalPrice: 3500 * 4,
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      id: uid(),
      roomId: 'room-003',
      guestName: 'Devon Lane',
      guestEmail: 'devon.lane@example.com',
      guestPhone: '+91 98765 43215',
      guestCity: 'Hyderabad',
      checkIn: offset(5),
      checkOut: offset(7),
      arrivalDate: offset(5),
      arrivalTime: '11:00',
      arrivalMode: 'ota',
      isForeignGuest: false,
      paymentMethod: 'gpay',
      mealPlan: 'AP',
      noOfRooms: 1,
      paxAdults: 3,
      paxChildren: 1,
      paxExtra: 0,
      status: 'confirmed',
      totalPrice: 2500 * 2,
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: uid(),
      roomId: 'room-103',
      guestName: 'Albert Flores',
      guestEmail: 'albert.flores@example.com',
      guestPhone: '+91 98765 43216',
      guestCity: 'Kolkata',
      checkIn: offset(-14),
      checkOut: offset(-10),
      arrivalDate: offset(-14),
      arrivalTime: '14:30',
      arrivalMode: 'travel-agent',
      isForeignGuest: true,
      paymentMethod: 'cash',
      mealPlan: 'CP',
      noOfRooms: 1,
      paxAdults: 2,
      paxChildren: 0,
      paxExtra: 0,
      status: 'checked-out',
      totalPrice: 4000 * 4,
      createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    },
    {
      id: uid(),
      roomId: 'room-004',
      guestName: 'Kristin Watson',
      guestEmail: 'kristin.watson@example.com',
      guestPhone: '+91 98765 43217',
      guestCity: 'Jaipur',
      checkIn: offset(-2),
      checkOut: offset(0),
      arrivalDate: offset(-2),
      arrivalTime: '10:00',
      arrivalMode: 'walkin',
      isForeignGuest: false,
      paymentMethod: 'cash',
      mealPlan: 'EP',
      noOfRooms: 1,
      paxAdults: 2,
      paxChildren: 0,
      paxExtra: 0,
      status: 'checked-out',
      totalPrice: 2500 * 2,
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
  ];
}
